# Generated by Django 4.2.5 on 2023-11-08 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppF23', '0003_course_interested'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
