# Generated by Django 4.2.5 on 2023-11-08 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppF23', '0004_order_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='levels',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
